### ISSUE TITLE
API structure to access data from city database

### ISSUE THREAD

**Issue by karansangha** [karansangha/Savecation#13]

**Comment by boomclicker** [comment]
you can use jsp and jdbc to connect database with api

**Comment by boomclicker** [comment]
require　'sqlite'　  
db　=　SQLite::Database.new
("library.db")　  
db.execute("select　title,
author　from　books")　do　|row|  
p　row　  
end　  
db.close
i am not sure this is work. this method use a part of ruby called DBI to allowed api get some data from database which use sqlite

**Comment by karansangha** [comment]
@boomclicker isn't JSP and JDBC for Java based application? Like JSP is Java Server Pages i think. Or am I on the wrong track here?

**Comment by boomclicker** [comment]
yeah it is not useful for ruby. dbi is work i think.it is for ruby.

**Comment by karansangha** [comment]
hmm. 🤔 

I think just normal routes coupled with returning a JSON object with related data should be good enough for our purposes. 

For example: [https://www.codementor.io/kristophmatthews/how-to-configure-your-first-rails-rest-api-du1084ym0](https://www.codementor.io/kristophmatthews/how-to-configure-your-first-rails-rest-api-du1084ym0)

**Comment by boomclicker** [comment]
yeah.i think this is work
