### ISSUE TITLE
The admin stories don't work

### ISSUE THREAD

**Issue by karansangha** [karansangha/Savecation#44]
First, I logged into an admin account with the credentials you provided ("hello@hello.com"). The link "http://pure-coast-27115.herokuapp.com/cities" works, but upon trying to add a new city, your app gives an error.

**Comment by karansangha** [comment]
@boomclicker can u look into this

**Comment by boomclicker** [comment]
it is work now。 i fixed it yesterday

**Comment by karansangha** [comment]
okey! 😄
